default_language_version:
    python: python3.10

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: trailing-whitespace
    - id: check-added-large-files
    - id: check-toml
    - id: check-yaml
      args:
      - --unsafe
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: forbid-new-submodules
    - id: no-commit-to-branch
      args: [--branch, staging, --branch, main]
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.9
  hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi ]